name: Docker image release

on:
    push:
        tags:
            - '*'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout PR
                uses: actions/checkout@v2

            -
                name: Get the version
                id: get_version
                run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -
                name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GIT_AUTH_TOKEN }}

            -
                name: Docker build and push
                uses: docker/build-push-action@v2
                with:
                    context: .
                    target: prod
                    tags: |
                        ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
                        ghcr.io/${{ github.repository }}:latest
                    push: true
                    secrets: |
                        GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
